### ISSUE TITLE
Crash app after success logout.

### ISSUE THREAD

**Issue by arturiosRoom4** [leoMehlig/TDLib-iOS#2]
Crash app after success logout.
![Screen Shot 2019-08-21 at 4 04 36 PM](https://user-images.githubusercontent.com/52455907/63434430-bc1b7800-c42d-11e9-8ddf-5b95d3736454.png)

**Comment by leoMehlig** [comment]
I also had that issue. There was some problem with the log if I remember correctly. Could you maybe send the error log. You should find it in the application data when you run it in the simulator.

**Comment by arturiosRoom4** [comment]
Can you provide more detailed information about error log? I can't find it

**Comment by leoMehlig** [comment]
When you run the app in the simulator, all the app data is stored in a dir on the Mac. More info [here](https://stackoverflow.com/questions/1108076/where-does-the-iphone-simulator-store-its-data).

Somewhere in there should be a log files. Sometimes you get more info there.

**Comment by arturiosRoom4** [comment]
I found system.log
[system.log](https://github.com/leoMehlig/TDLib-iOS/files/3551191/system.log)

**Comment by leoMehlig** [comment]
Sorry for the late response. I don't think that this is the correct log file. I only see system logs in there and no logs from TDLib.

**Comment by leoMehlig** [comment]
I just released v1.5. Can you check again with the new version.

**Comment by arturiosRoom4** [comment]
Ok, i will test soon.

**Comment by digabriel** [comment]
Hi @leoMehlig. Thanks for your awesome library!

I'm still getting this issue when logging out. I'm currently using the 1.6.0 version.

<img width="1417" alt="Screen Shot 2020-04-03 at 18 46 45" src="https://user-images.githubusercontent.com/509952/78407640-ad0fc180-75db-11ea-8d3e-8004d45fce9c.png">

**Comment by nikit6000** [comment]
This error occurs because td_json_client_receive is still receiving data when the td_json_client_destroy is called. 

here is a quick fix

```swift

    //TDJsonClient

    public func close() {
        
        if self.isListing {
            self.isListing = false
        }
        
        queue.sync { [weak self] in
            
            guard let strongSelf = self else {
                return
            }
    
            if strongSelf.isRunning {
                print("Closing client", strongSelf.rawClient)
                strongSelf.isRunning = false
                td_json_client_destroy(client: strongSelf.rawClient)
            }
                
            
        }
        
        
    }

```

**Comment by leoMehlig** [comment]
@nikit6000 Would you be able to create a PR for this?

**Comment by nikit6000** [comment]
@leoMehlig Yes, i can create Pull Reques rigth now
